POST https://pills-reminder.quentinaslan.fr/api/sendNotification
Content-Type: application/json

{
  "username": "Quentin",
  "title": "Title of the notification",
  "body": "Content of the notification"
}
